default: &default
  adapter: mysql2
  encoding: utf8
  database: proxy
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: proxy_development

test:
  <<: *default
  database: proxy_test
